@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODkwMTk2OTF9.YuA54yB57KMInLDdURH6KTZjxKO-tL6X2qMej_bzR-4

### Session Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mike89@test.com",
  "password": "password"
}

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Casey",
  "last_name": "Bruchwalski",
  "email": "casey99@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### User Update
PATCH http://localhost:3000/users/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "city": "Los Angeles",
  "state": "California"
}

### User Show
GET http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### CarWash Index
GET http://localhost:3000/car_washes.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### CarWash Show
GET http://localhost:3000/car_washes/ChIJmcYQGKjxNIgRQ_0dAxm5YAc.json
Content-Type: application/json
Authorization: Bearer {{jwt}}